# server {
#     listen 80;

#     location / {
#         # 'client' ang gagamitin nating pangalan sa docker-compose mamaya
#         proxy_pass http://client:5173;
        
#         # Eto ang sikreto para sa Live Reload (HMR)
#         proxy_http_version 1.1;
#         proxy_set_header Upgrade $http_upgrade;
#         proxy_set_header Connection "upgrade";
#         proxy_set_header Host $host;
#     }
# }

server {
    listen 80;
    
    location / {
        # Para sa dev, i-proxy ang lahat sa Vite dev server
        proxy_pass http://client-app:5173; 
    }

    # 🔥 DITO ANG PROXY PAPUNTA SA BACKEND NGIX 🔥
    location /api/ {
        proxy_pass http://backend-nginx:80;
        proxy_set_header Host $host;
        # ... iba pang headers
    }
}



