export const users = [
  {
    id: 1,
    name: "Alice Johnson",
    email: "alice@example.com",
    role: "admin",
    isActive: true,
  },
  {
    id: 2,
    name: "Bob Smith",
    email: "bob@example.com",
    role: "user",
    isActive: true,
  },
  {
    id: 3,
    name: "Clara Lee",
    email: "clara@example.com",
    role: "moderator",
    isActive: false,
  },
  {
    id: 4,
    name: "David Kim",
    email: "david@example.com",
    role: "user",
    isActive: true,
  },
  {
    id: 5,
    name: "Eva Brown",
    email: "eva@example.com",
    role: "user",
    isActive: false,
  },
  {
    id: 6,
    name: "Frank Wright",
    email: "frank@example.com",
    role: "admin",
    isActive: true,
  },
  {
    id: 7,
    name: "Grace Hall",
    email: "grace@example.com",
    role: "moderator",
    isActive: true,
  },
  {
    id: 8,
    name: "Henry Ford",
    email: "henry@example.com",
    role: "user",
    isActive: false,
  },
  {
    id: 9,
    name: "Ivy Brooks",
    email: "ivy@example.com",
    role: "user",
    isActive: true,
  },
  {
    id: 10,
    name: "Jack Daniels",
    email: "jack@example.com",
    role: "admin",
    isActive: true,
  },
];
