# /server/Dockerfile.dev
FROM node:20-alpine

# Install curl para sa healthcheck
RUN apk add --no-cache curl

WORKDIR /app

# Install pnpm globally
RUN npm install -g pnpm

# Copy package files
COPY package.json pnpm-lock.yaml* ./

# Install dependencies
RUN pnpm install

# Copy source code
COPY . .

# I-expose ang Express port (Default: 5000)
EXPOSE 5000

# Gamitin ang start:dev (karaniwang nodemon o ts-node-dev)
CMD ["pnpm", "run", "start:dev"]