events {}
http {
    server {
        listen 80;

        # Papunta sa Frontend setup mo
        location / {
            proxy_pass http://client_proxy:80; # 'frontend' ang container_name sa client compose mo
            proxy_set_header Host $host;
        }

        # Papunta sa Backend setup mo
        location /api {
            proxy_pass http://server_proxy:80; # 'nginx' ang container_name sa server compose mo
            proxy_set_header Host $host;
        }
    }
}